import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

const messages = [
  // Short
  "Liming...",
  "Reasoning...",
  "Macoing...",
  "Hustling by the market...",
  "Heading to the bus park...",
  "Catching a minibus...",
  "Holding a lil vibes...",
  "Cooling out...",
  "Passing through Stabroek...",
  "Swinging by Bourda...",
  "Walking the seawall...",
  "Stopping by the rum shop...",
  "Buying two beers...",
  "Getting some cutters...",
  "Whining pun a ting...",
  "Don't seh 40...",
  "Frying plantain...",
  "Stirring cook-up rice...",
  "Warming pepperpot...",
  "Peeling cassava...",
  "Cutting lime for the drinks...",
  "Filling the igloo cooler...",
  "Looking for a red mango...",
  "Checking on the pot...",
  "Making a market run...",
  "Catching the last car...",
  "Listening for the kiskadees...",
  "Watching the rain clouds...",
  "Waiting till breeze come...",
  "Sharing a small piece...",
  "Saving a plate for later...",
  "Holding strain...",
  "Moving just now...",

  // Long
  "Heading to the bus park and hoping the minibus full up quick...",
  "Liming by Stabroek and talking bare nonsense...",
  "Stopping by the rum shop and buying two cold beers...",
  "Getting some cutters because the drinks cyan go down so plain...",
  "Whining pun a ting like the speaker hit the right tune...",
  "Trying hard not to seh 40 and still nearly letting it slip...",
  "Making a quick market run before the rain start fall...",
  "Walking the seawall and catching a proper evening breeze...",
  "Checking if the pot done before everybody start asking for food...",
  "Saving a lil cook-up rice because somebody always coming over...",
  "Warming pepperpot like it tasting even better the next day...",
  "Passing through Bourda and trying not to buy more than planned...",
  "Waiting on the bus and watching everybody else hustle through...",
  "Cooling out under the gallery till the heat ease up...",
  "Cutting lime and setting up drinks for the whole set...",
  "Listening to old stories that start with 'leh me tell yuh'...",
  "Holding a corner by the shop and catching up on everything missed...",
  "Trying to leave the lime but one more story keep starting...",
  "Watching the road flood a lil and still planning how to get through...",
  "Packing up snacks like the trip gon' take all day...",
  "Looking for the best plantain and pretending it is a quick stop...",
  "Waiting till everybody ready, which means waiting plenty longer...",
  "Moving just now, but first taking one last small sit-down...",

  // Guyanese Proverbs
  "All cassava get same skin but all nah taste same way...",
  "Baby who ah cry ah house and ah door ah same thing...",
  "Belly full behind drunk...",
  "Big tree fall down, goat bite he leaf...",
  "Bush get ears and dutty get tongue...",
  "Cat foot soft but he ah scratch bad...",
  "Cuss when yuh ah guh, nah wheh yuh ah come out...",
  "Contrary breeze ah mek crow and eagle light on one line...",
  "Cow deh a pasture he nah remember seh dog and butcher deh till he see am...",
  "Cat a ketch rat, but he a teef he massa fish...",
  "Clath ah easy fuh dutty but hard fuh wash...",
  "Dah mouth dat man tek fuh court woman, ah de same mouth he ah tek an put she ah door...",
  "Don't mind how bird vex, it can't vex with tree...",
  "Dog buy rum, cow drink am, hog in sty get drunk...",
  "Every rope gat two ends...",
  "Every fowl feed pon he own craw...",
  "Every best friend get a next best friend...",
  "Every bush a man night time...",
  "Fish ah deh ah watah but nah ah dam tap...",
  "Fish ah play ah sea, he nah know watah ah boil fuh am...",
  "Fish and cast-net nah friend...",
  "Good gubby nah ah float ah tap...",
  "Hungry nah know bam-by...",
  "If yuh finger get sore, nah tek am and throw way...",
  "If yuh eye nah see, yuh mouth nah must talk...",
  "If cow-man pass wild meat whah mek me must pick up am...",
  "It nah good to shove yuh foot in every stocking...",
  "If me bin know always deh behind de door...",
  "If yuh nah get wing, nah ah guh a bird sport...",
  "If dutty ah deh ah roof tap, yuh barrel ah catch am...",
  "If oil ah float watah deh ah battam...",
  "If yuh plant plantain yuh can't reap cassava...",
  "If trousers say massah teef, yuh can't doubt am...",
  "Lil finger point to de big thumb and sey nah guh...",
  "Lil boy nah climb ladder to turn big man...",
  "Lil ah sick, big a get better...",
  "Man strength deh ah he hand, woman strength deh a she mouth...",
  "Mouth cut trousers nah ah fit Massa...",
  "Macaw ask parrot if mango ripe, he say one, one...",
  "Moon ah run till daylight ketch am...",
  "Nah all who guh a church house ah guh fuh pray...",
  "Nah tek yuh mattie eye fuh see...",
  "Nah one time a fire mek peas boil...",
  "Nah because dog ah play with yuh he nah bite yuh...",
  "Nah every crab hole get crab...",
  "Nah every big head get sense...",
  "Nah mind how pumpkin vine run, he must dry up one day...",
  "Nah put all two foot in river if yuh want see how he deep...",
  "Nah everything scholar know he learn from teacher...",
  "Never guh a store ah night fuh buy black cloth...",
  "No good carpenter does get good wuk bench...",
  "Nobody want dutty powder...",
  "One man money mek too much man cry...",
  "One kiss nah done lips...",
  "Orange yellow but yuh nah know if he sweet...",
  "Only knife ah know whah in pumpkin belly...",
  "Rain ah fall ah roof yuh put barrel fuh ketch am...",
  "Shame face ah feel like cent ice...",
  "Some pork-knockers does only clear track fuh monkey run race...",
  "Seven years nah too much fuh wash speck off ah bird neck...",
  "Slow fire ah boil hard cow-heel...",
  "Tongue nah gat teeth but he ah bite fuh true...",
  "Turtle can't walk if he nah push he head outa he shell...",
  "Turtle nah want trouble mek he walk with he house pon he back...",
  "Too much sit down ah bruck trousers...",
  "The looks ah de pudding is not de taste...",
  "Vice nah hurt but conscience ah hurt yuh...",
  "Vex nah gat plaster fuh passion...",
  "Wasteful man money ah guh like butter in de sun...",
  "When man mek heself sugar he mattie ah suck am...",
  "When yuh buy ah dutty calico yuh gat fuh wear am till it tear...",
  "When yuh play out all yuh trump cards yuh gat to lose till game done...",
  "When yuh dead yuh nah sabee, and when yuh sabee yuh dead...",
  "When man done suck cane he dash peeling pan ground...",
  "When Mumma dead family done...",
  "When dog hungry he ah nyam calabash...",
  "When gaulding see fish he forget seh gun deh...",
  "When yuh deh in bad luck wet paper self ah cut yuh...",
  "When water throw away ah ground yuh can't pick am up...",
  "When coconut fall from tree he can't fasten back...",
  "When two big bottle deh ah table lil one nah business deh...",
  "Whah hurt eye does mek nose run water...",
  "When you want fuh swim river yuh gat fuh plunge inside fuss...",
  "Yuh tel tara and tara tell tara...",
  "Youth nah ah weary but he ah fall down...",
  "Yuh can't chew bone with gum...",
  "Yuh can't fatten cow fuh another man butcher...",
  "Yuh can't drink mauby and belch beer...",
  "Yuh can't suck cane and blow whistle...",
  "Yuh gat fuh blow yuh nose where yuh stump yuh toe...",
  "One, one dutty build dam...",
  "Dance a battam watch a tap...",
  "Never cuss bridge that you cross...",
  "Monkey dress e pickney till he spoil...",
  "All skin teeth nah laugh...",
];

function pickRandom(): string {
  return messages[Math.floor(Math.random() * messages.length)];
}

export default function (pi: ExtensionAPI) {
  pi.on("turn_start", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(pickRandom());
  });

  pi.on("turn_end", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(); // Reset for next time
  });
}
